# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-06-22 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mob_app', '0002_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('m_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile_name', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=200)),
                ('rom', models.CharField(max_length=200)),
                ('camera', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('battery', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('picture', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
