# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-06-24 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mob_app', '0003_auto_20220622_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField()),
                ('mobile_name', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=200)),
            ],
        ),
    ]
